#pragma once

// Generated by cp77ida.py on 2024-01-31 for Cyberpunk 2077 v.2.11
// DO NOT MODIFY. USE tools\ida\scan.py TO GENERATE THIS FILE.

#include <cstdint>

namespace Red::Address
{
constexpr uintptr_t ImageBase = 0x140000000;

constexpr uintptr_t Main = 0x1406A4828 - ImageBase; // 40 55 53 48 8D AC 24 ? ? ? ? 48 81 EC ? ? ? ? FF 15 ? ? ? ? E8, expected: 1, index: 0

constexpr uintptr_t StatsDataSystem_InitializeRecords = 0x1401F52BC - ImageBase; // 48 89 5C 24 ? 55 56 57 41 56 41 57 48 8B EC 48 83 EC ? 48 8B F9 E8 ? ? ? ? 48 8B C8 48 8B 10 4C 8B 42 ? 48 BA 8D 46 27 9F 31 66 30 74, expected: 1, index: 0
constexpr uintptr_t StatsDataSystem_InitializeParams = 0x140BA9CE0 - ImageBase; // 40 55 53 56 57 41 56 48 8B EC 48 83 EC ? 8B 91 ? ? ? ? 48 8D B1 ? ? ? ? 48 8B F9 39 56 ? 73 ? 48 83 64 24, expected: 1, index: 0
constexpr uintptr_t StatsDataSystem_GetStatRange = 0x140151238 - ImageBase; // 48 89 5C 24 ? 48 89 6C 24 ? 48 89 74 24 ? 57 48 83 EC ? 41 8B F0 48 8B FA 48 8B E9 41 81 F8 ? ? ? ? 73, expected: 1, index: 0
constexpr uintptr_t StatsDataSystem_GetStatFlags = 0x1403554C4 - ImageBase; // 48 89 5C 24 ? 48 89 74 24 ? 57 48 83 EC ? 8B FA 48 8B F1 81 FA ? ? ? ? 73, expected: 1, index: 0
constexpr uintptr_t StatsDataSystem_CheckStatFlag = 0x1403554A8 - ImageBase; // 40 53 48 83 EC 20 41 8B D8 E8 ? ? ? ? 85 C3 0F 95 C0 48 83 C4 20 5B C3, expected: 1, index: 0

constexpr uintptr_t TweakDB_Init = 0x140897CE0 - ImageBase; // 48 89 5C 24 ? 57 48 83 EC ? 4C 8B 42 ? 48 8B D9 BF ? ? ? ? 4D 85 C0 74 ? 65 48 8B 04 25 ? ? ? ? 4D 8B 00 48 8B 10 41 8A 40 ? 88 04 17 48 8B 41 08 8B 08 85 C9 74 ? E8 ? ? ? ? E8, expected: 1, index: 0
constexpr uintptr_t TweakDB_Load = 0x140528F6C - ImageBase; // 48 89 5C 24 ? 48 89 7C 24 ? 55 48 8B EC 48 ? EC ? ? ? ? 48 8B F9 48 8B DA 48 8B 0D, expected: 1, index: 0
constexpr uintptr_t TweakDB_CreateRecord = 0x14018F0D8 - ImageBase; // 48 89 5C 24 08 48 89 74 24 10 57 48 83 EC 30 8B C2 49 8B D8 83 E0 1F, expected: 1, index: 0

constexpr uintptr_t TweakDBID_Derive = 0x14018EF44 - ImageBase; // 48 89 5C 24 ? 48 89 74 24 ? 57 48 83 EC ? 33 C0 4D 8B C8 48 8B F2 4D 85 C0 74, expected: 1, index: 0
}
